module.exports = {
    build: {
        html: 'dev/' /* path for ready htmls */,
        js: 'dev/assets/js/' /* path for ready js */,
        css: 'dev/assets/css/' /* path for ready css */,
        img: 'dev/assets/images/' /* path for ready images */,
        media: 'dev/assets/media/' /* path for ready media-files */,
        svg: 'dev/assets/svg/' /* path for ready svg */,
        fonts: 'dev/assets/fonts/' /* path for ready fonts */,
    },
    src: {
        common: 'src/' /* path for source folder */,
        svg: 'src/svg/' /* path for source svg folder */,
        svg_sprite: 'src/svg/sprite/*.svg' /* path for svg sprite files */,
        svg_files: 'src/svg/**/*.svg' /* path for all svg files */,
        media: 'src/media/**/*.*' /* path for source media files */,
        fonts: 'src/fonts/**/*.*' /* path for source fonts folder */,
        js_partials: 'src/js/partials/' /* path for source js partials folder */,
        js: 'src/js/' /* path for source js folder */,
        html: 'src/*.html' /* path for source html files */,
        html_partials: 'src/html/' /* path for source html files */,
        sass: 'src/sass/**/*.+(sass|scss)' /* path for source sass files */,
        img: 'src/images/**/*.+(jpg|jpeg|png|gif)' /* path for source images files */,
    },
    watch: {
        html: 'src/*.html' /* path for watch html files */,
        js: 'src/js/**/*.js' /* path for watch js files */,
        sass: 'src/sass/**/*.scss' /* path for watch sass files */,
        svg: 'src/svg/**/*.svg' /* path for watch svg files */,
        svg_no_sprite: '!src/svg/**/sprite.svg' /* path for exclude sprite-svg */,
        img: 'src/images/**/*.+(jpg|jpeg|png|gif)' /* path for watch image files */,
    },
    clean: 'dev/' /* path for browsersync directory */,
    port: '4004',
};
